\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename industria.info
@settitle The Industria Libraries Manual
@c %**end of header

@c info: makeinfo industria
@c html: makeinfo --no-split --html industria
@c pdf: texi2pdf industria.texinfo

@ifinfo
@macro rnrs{}
R6RS
@end macro
@end ifinfo

@ifnotinfo
@macro rnrs{}
R@math{^6}RS
@end macro
@end ifnotinfo

@ifhtml
@unmacro rnrs
@macro rnrs{}
@html
R<sup><small>6</small></sup>RS
@end html
@end macro
@end ifhtml

@syncodeindex fn cp

@copying
This manual is for the Industria libraries, a collection of
@rnrs{} Scheme libraries.

Copyright @copyright{} 2010, 2011, 2012 G@"oran Weinholt @email{goran@@weinholt.se}.

@quotation
Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
@end quotation
@end copying

@c Same category SLIB uses
@dircategory The Algorithmic Language Scheme
@direntry
* Industria: (industria).          The Industria libraries
@end direntry

@titlepage
@title The Industria Libraries Manual
@author G@"oran Weinholt

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top Industria

@insertcopying

@end ifnottex

@menu
* Getting started::    Installation and usage
* Library reference::  How to use the individual libraries
@c * Copying::            Your right to keep and arm bears
* Demo programs::      Demonstrations of some libraries
* Index::              Index of concepts, functions, etc
@end menu

@node Getting started
@chapter Getting started

@menu
* Installation::       Where to put all the files
* Usage::              How to make it go
* Conflicting names::  When two exports have the same name
@end menu

@include starting.texinfo

@node Library reference
@chapter Library reference

@menu
@c * archive::            File archive utilities
@c * assembler::          Machine code assemblers
* binfmt::             Executable file format utilities
* compression::        Data decompression
* crypto::             Cryptographic primitives
* disassembler::       Machine code disassemblers
* net::                Network protocols
* struct::             Binary structure utilities
* text::               Textual structure utilities
* types::              Data types and utilities
@end menu

@include binfmt.texinfo
@include compression.texinfo
@include crypto.texinfo
@include disassembler.texinfo
@include net.texinfo
@include struct.texinfo
@include text.texinfo

@include types.texinfo
@include demos.texinfo

@node Index
@unnumbered Index
@printindex cp

@bye
